database:
  host: 127.0.0.1
  user: root
  password: "410014"
  db: appliances
redis:
  host: 127.0.0.1
  port: 6379
  db: 0
chaojiying:
  username: "y455789298"
  password: "m.j.y.123098"
  soft_id: "903564"
weibo:
  username: "18086740017"
  password: "m.j.y.123098"
